### ISSUE TITLE
entering url problem when using a variable

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#10]
Using the URL field in Request, entering a variable is not working

writing `{{ }}` then pressing left arrow to be in the middle and writing server ... only `s` will be inside, the rest will be written to the right.

I have an env `server` => `http://localhost:3000` that I want to use.

**Comment by subasraj** [comment]
What Flashpost version are you using please use 1.1.54 and above. I tried to recreate this issue and cannot do so. Closing this issue.

**Comment by BananaAcid** [comment]
It is the newest. For Thunder client it works on the same editor. Testet it on other installations/devices, with no problems. I would guess, it is related to another extension on that one device.

**Comment by BananaAcid** [comment]
@subasraj interesting: had this very same problem on windows as well - but problem did vanish after switching to the other tabs/back to code ... next time, I try to record the screen
