### ISSUE TITLE
(New Feature)support including values from .env file from the project

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#11]
.. so `NODE_ENV` = `production` (SERVER_URL and what not) can be used as variable directly 

probably with an option: `Enable automatic inclusion of '.env' file` which would be injected before the environment values

**Comment by subasraj** [comment]
will you use this same variable format {{NODE_ENV}}

**Comment by BananaAcid** [comment]
I would then use it - if available.

Commonly .env files in node based projects hold a lot of configuration already. Not needing to copy paste all of it into the „environment“ tab each time something changes in the env file would be great.

**Comment by subasraj** [comment]
@BananaAcid I have made the change. Please try Flashpost version 1.1.55. I have also add a setting to control this .env see image below

![image](https://github.com/subasraj/flashpost-support/assets/25518421/960d9973-a2c2-4358-9fa8-7665d498cfcd)

**Comment by subasraj** [comment]
@BananaAcid Ddi you try this .env change ? please let me know if you have tested it

**Comment by BananaAcid** [comment]
@subasraj Yes testet - works.
Seems like it is case sensitive.

But: I had to reload the VSCode to get it to update the keys from the `.env`-file for the green highlighting in the URL.
`send` worked right away. and it turned green after pressing send as well. Maybe something to optimize - but feature works!!!

**Comment by subasraj** [comment]
The .env file loading works when you open the request. For green highlighting close and open request tab.
