### ISSUE TITLE
(New Request) generating code for fetch would be nice

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#12]
I know, code will be generated for `axios`, but `fetch` would be perfect and more general to be used (node, browser, polyfill, ...)

**Comment by subasraj** [comment]
It's already there please see this image below

![image](https://github.com/subasraj/flashpost-support/assets/25518421/641b987a-9614-4984-a493-21c19e3b01cc)

**Comment by BananaAcid** [comment]
Oh sorry - fasted feature addition i have ever seen ;)

**Comment by BananaAcid** [comment]
@subasraj was just checking them out ... and found PHP > fetch does show the curl version (I expected PEAR's HTTP_Request https://pear.php.net/manual/en/package.http.http-request.php )

and: I love seeing HTTPie there :)
