### ISSUE TITLE
pill contrast is really bad

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#13]
<img width="134" alt="Bildschirmfoto 2023-12-21 um 12 41 24" src="https://github.com/subasraj/flashpost-support/assets/1894723/692f9327-3d88-45d2-b1d2-f0f3541067c7">

changing the font color would probably be way better for readability. Me and my colleagues  I can barely read it.

**Comment by subasraj** [comment]
What theme are you using

**Comment by BananaAcid** [comment]
„Ayu“  Mirage.

https://marketplace.visualstudio.com/items?itemName=teabyii.ayu

Didn‘t actually think about it, as we all use the same one around here. 
Thinking about it: Is this extension using a default css-variable for the text color that is set by my theme?

**Comment by subasraj** [comment]
it's using color: "var(--vscode-foreground)"

**Comment by BananaAcid** [comment]
And for the pill color? Is it a fixed color? In that case, I believe, the foreground color for the pill should be a fixed one as well, to not cause problems for any theme.

**Comment by subasraj** [comment]
@BananaAcid  Fixed the Pill Color. Please try the latest version 1.1.56

**Comment by BananaAcid** [comment]
Sadly, does not seem to work. seems to be a problem on al MacOS, Windows seems fine. 

<img width="1828" alt="Bildschirm­foto 2023-12-23 um 16 13 56" src="https://github.com/subasraj/flashpost-support/assets/1894723/1b211921-f98f-4184-b8b2-312ea5b69891">

**Comment by subasraj** [comment]
I have a mac and it works properly

**Comment by BananaAcid** [comment]
> Yes its using the default css-variable for the text color that is set by your theme. it's using color: "var(--vscode-foreground)" Its the same for your workspace and same for Thunder client. Closing this issue.

@subasraj VSCode Inspector shows, it uses:

```css
.request-method-drop-down {
    /* ... */
    color: var(--button-text-color);
    /* ... */
}
```

you seem to reference (which does not seem to be applied ehen using the inspector)
```css
.request-method-drop-down option {
  color           : var(--text-color);
  /* ... */
```

**Comment by subasraj** [comment]
Changed request-method-drop-down. mtd-wrapper3 in my code is already changed. Please try the latest version again.

**Comment by BananaAcid** [comment]
Yes works flawlessly - switched themes -- all fine
