### ISSUE TITLE
(New Change)Textmode / Raw input for headers 

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#15]
would be great to have a button to switch to a textbox for inputting headers and maybe params as well

**Comment by BananaAcid** [comment]
Just as an addition, it would be great. ThunderClient uses a button tonswitch from table to Textfield. Is great for coping the headers as multiline string in and out

**Comment by subasraj** [comment]
@BananaAcid I have made the changes, please try the latest version 1.1.57

![image](https://github.com/subasraj/flashpost-support/assets/25518421/0cc439e7-3aca-4c12-9435-771e8ad01db9)
![image](https://github.com/subasraj/flashpost-support/assets/25518421/dd606fcc-6914-4c50-8662-be16aa3bca67)

**Comment by BananaAcid** [comment]
Hi thats pretty cool, but there seems to be a bug: in the textwindow entered, the space after the colon is prepended to the value.
Also from converting from the table view to the textbox, the space is always missing after the colon.

HTTP Headers in consist of `key`+ `colon` + `space` + `value`.  (example use: coping from the Chrome Inspector or form HTTPie or from CURL or WGET) see: [List of HTTP header fields](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)

![image](https://github.com/subasraj/flashpost-support/assets/1894723/05dc2b00-e77e-4750-a59a-f2cdca495d9c)
![image](https://github.com/subasraj/flashpost-support/assets/1894723/0018c341-631a-4125-8fd6-960abcab93d2)

**Comment by subasraj** [comment]
@BananaAcid "**_Params and Headers Bulk editing_**" is behaving the same way as in Postman, please try in Postman. I don't see an issue with that. Fixed the bug in body->Raw tab in version 1.1.59

**Comment by BananaAcid** [comment]
Headers with space: ThunderClient also does a have space.
I found several discussions to fix this In postman as well, since the http protocol requires the space and copying headers from browsers naturally contains them too.

---

for body:

the text areas work. 

I miss interpreted the RAW tab.

It could fit the other bulk edit option, if the `form` tab would have the same way of editing (as with my previous comment)

**Comment by subasraj** [comment]
> Headers with space: ThunderClient also does a have space. I found several discussions to fix this In postman as well, since the http protocol requires the space and copying headers from browsers naturally contains them too.
> 
> for body:
> 
> the text areas work.
> 
> I miss interpreted the RAW tab.
> 
> It could fit the other bulk edit option, if the `form` tab would have the same way of editing (as with my previous comment)

@BananaAcid 
1. I have Fixed the issue in the headers for space after the colon, Please retest with the latest version of Flashpost
2. I have added bulk edit functionality for body-> form tab
