### ISSUE TITLE
(New Request) description text field for requests would be helpful

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#16]
It would be great to have an additional description text field for each api request for documentation purposes.

Just for display, no logic needs to be attached to it. Otherwise, all description needs to go into the caption.

**Comment by subasraj** [comment]
Its already there called notes on the right hand side. Please see image below.

![image](https://github.com/subasraj/flashpost-support/assets/25518421/715ff752-28ca-4ca7-857f-8b7b81b36746)

**Comment by BananaAcid** [comment]
@subasraj yes notes seems to to be used for larger text but would work as well - is there an option to have it show up right below the request name and the method pill for each request in the collections explorer to the left?

**Comment by subasraj** [comment]
@BananaAcid sorry we cannot move it to the left. It’s the request option area.

**Comment by BananaAcid** [comment]
@subasraj 

My idea (Photoshop):
![flashpost_shortdescription_idea](https://github.com/subasraj/flashpost-support/assets/1894723/313052a3-4e31-4fdd-b651-9c0b374dd693)

Original
![image](https://github.com/subasraj/flashpost-support/assets/1894723/fbc05a73-c34c-4f05-9880-1d419fdaa245)

**Comment by subasraj** [comment]
@BananaAcid

**Comment by BananaAcid** [comment]
Good idea - this would work

**Comment by subasraj** [comment]
> Good idea - adding with the options this would work, but the alt text would require hovering each item. Having it display always would be way more helpful.

@BananaAcid please try now. I can do only alt text for now.
