### ISSUE TITLE
(New Request) Please support Chinese display.

### ISSUE THREAD

**Issue by joyous-coder** [subasraj/flashpost-support#17]
The Chinese characters in the response are displayed as garbled code, as shown in the following picture.
![image](https://github.com/subasraj/flashpost-support/assets/42910684/fee0330a-26ef-4250-8fae-c77a796c6506)
![image](https://github.com/subasraj/flashpost-support/assets/42910684/959a5a34-072e-4bef-a798-831fb8b35484)

The test website is "http://www.baidu.com"

**Comment by subasraj** [comment]
@joyous-coder I have added support for Chinese characters now. Please update to the latest version and try again.

**Comment by joyous-coder** [comment]
@subasraj It works. Nice job and 3Q!!!
