### ISSUE TITLE
Import Collection from OpenAPI 2.0/3.0 Swagger Files

### ISSUE THREAD

**Issue by SxMShaDoW** [subasraj/flashpost-support#2]
Hi,

It would be great to add support for importing OpenAPI swagger.json/yaml files.

Example 2.0 - https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/api-with-examples.json
Example 3.0 - https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.json

**Comment by subasraj** [comment]
Hi,
Please install the latest version of Flashpost 1.1.48 I have added the option to import OpenAPI/Swagger files.

Thanks,
Subas

**Comment by subasraj** [comment]
@brandsr Can you please share a sample file for "/api/v1/:hostname/:action"

**Comment by brandsr** [comment]
Hi @subasraj ,

find attached a small example. I would expect that when opening the `hostname get` request to have `Params` prefilled with the examples for the path parameters `hostname` and `action`. And when sending de request (after optionally modifying the values) the URI is properly formatted with replaced param values.

(ergo: an uri in openapi does not only have query params, but also (and most often) path params)
[openapi3.1.yml.zip](https://github.com/subasraj/flashpost-support/files/13686537/openapi3.1.yml.zip)

**Comment by subasraj** [comment]
@brandsr I have added code for "path params" It will be the same as in postman. Please update to version 1.1.50 and try again. Also, the file you sent me "openapi3.1.yml doesn't work and getting exceptions in Thunder Client.

**Comment by subasraj** [comment]
Closing this. Please open a new one if needed for any changes or bug fixes.

**Comment by brandsr** [comment]
> @brandsr I have added code for "path params" It will be the same as in postman. Please update to latest version and try again. Also, the file you sent me "openapi3.1.yml doesn't work and getting exceptions in Thunder Client.

The example file was only imported in your extension, not in ThunderClient. 👍
