### ISSUE TITLE
Share collection/environment changes trough git

### ISSUE THREAD

**Issue by mikkelkn2d** [subasraj/flashpost-support#20]
Is it possible to share collections and environments with team members trough Git? 
So that once a member updates/adds a new request or environment, you don't have to re-import the collection to see the new request?

**Comment by subasraj** [comment]
Yes, you can save it on your project workspace and commit it to Git. From Flashpost settings use the "Save Data To Workspace" option. You can also save to a relative path in your project using " Workspace Data Relative Path".

![image](https://github.com/subasraj/flashpost-support/assets/25518421/3fc4571a-b241-4852-a72e-567e4ef3128a)
