### ISSUE TITLE
Suggestion: Comment differences with Thunder Client

### ISSUE THREAD

**Issue by tony19** [subasraj/flashpost-support#21]
Given that this extension appears to be a clone of Thunder Client, it would help to clearly show the differences (if any) and the main reason to pick this extension.

Something like this:

> It's completely FREE unlike Thunder Client, which has price tiers.

It took me a bit of scouring through reviews to determine that.

Also would be nice to open-source this.

**Comment by subasraj** [comment]
Ok will try.
