### ISSUE TITLE
Any plans to opensource the project?

### ISSUE THREAD

**Issue by rayrapetyan** [subasraj/flashpost-support#22]
I am confident that by open-sourcing it, your user base could effortlessly expand from 800 to 800K within a year.

**Comment by subasraj** [comment]
Ok will try

**Comment by mrowrpurr** [comment]
+1

I have already wanted to provide a contribution and was disappointed when I could not find the source code anywhere on GitHub.

Please reach out to the community if you need help! Great app, it's a life saver.

**Comment by Niclassg** [comment]
You did mark this issue as completed but I cannot find the source code :(

**Comment by krokand** [comment]
> Ok will try

This is already a very promising project, but I have reservations about the source code being closed. When you mentioned that you would try to make it open source and then closed this issue, it raised concerns for me. As a result, I'm hesitant to input API secrets into this extension and will likely explore other alternatives.

I was looking forward to collaborating with you and others to develop this extension into a full-fledged replacement for Postman and Thunder Client. Open-sourcing the project could not only alleviate security concerns but also encourage community contributions that accelerate its development. I hope you'll reconsider making the source code available, as it would greatly enhance trust and encourage wider adoption.

**Comment by BananaAcid** [comment]
We had to remove it recently from all projects and were prohibited to use it any further due to security concerns raised in an audit, because of the this being closed source.
