### ISSUE TITLE
Usage of '%' character in query param value not working

### ISSUE THREAD

**Issue by dcampillo** [subasraj/flashpost-support#24]
The usage of a '%' is not supported, which mean no value can contain '%'

- A param value 'test%2024' is interpreted and stored as 'test24'. it seems that %20 is intepreted as an the HTML encoded value for space.

- A param value such 'test%test' is just stored.

**Comment by subasraj** [comment]
@dcampillo I have made the changes. Please try the latest version 1.1.72

**Comment by dcampillo** [comment]
Just tested the version 1.1.73, and the bug is fixed.

THANKS a lot! This extension is awesome!
