### ISSUE TITLE
Save Data To Workspace Bug

### ISSUE THREAD

**Issue by Acturus** [subasraj/flashpost-support#25]
When I enable this option of the extension, the request address bar disappears and I cant edit the URL.

When I toogle off this option, and restart VSCode the bar reappears.

I'm on Windows 11, lastest VS Code.

**Comment by subasraj** [comment]
@Acturus I tried to recreate this issue and was not able to. Please send me some screenshots.

**Comment by subasraj** [comment]
@Acturus Since i did'nt hear from you, looks like its a no issue.
