### ISSUE TITLE
1.1.76 - OAuth 2 token generation no longer works

### ISSUE THREAD

**Issue by mrowrpurr** [subasraj/flashpost-support#26]
<img width="1421" alt="image" src="https://github.com/subasraj/flashpost-support/assets/87039589/5c40a2bb-6e9e-4fc8-9371-360e9f9a2340">

Trying to generate an OAuth 2 token stopped working in 1.1.76

My server no longer sees a request providing the Client Credentials

Note, I am trying to generate using the following fields/settings:
- Client Credential
- As Request Body

<img width="1026" alt="image" src="https://github.com/subasraj/flashpost-support/assets/87039589/4de4f9b8-ec52-4ac9-9091-6d5d012e624a">

**Comment by mrowrpurr** [comment]
Note: I have downgraded to 1.1.75 and it works great. Upgraded to 1.1.76 again and it fails again. Downgraded again and it works great again. Seems to be 1.1.76

**Comment by subasraj** [comment]
Works for me 
![image](https://github.com/subasraj/flashpost-support/assets/25518421/c8435213-8774-49ce-b86d-40b6075f5a8d)
