### ISSUE TITLE
Workspace path problem

### ISSUE THREAD

**Issue by kryopix** [subasraj/flashpost-support#27]
Hello,

First and foremost, great job on the Flashpost extension!

I wanted to bring to your attention a couple of issues we've encountered while using the extension in our team environment:

- The "Save to workspace" function isn't feasible for our team due to the inclusion of the user's home directory path in the saved files, rather than being relative to the current workspace of the repository. For instance, the saved file path appears as: {"filename":"/home/Username/workspace/tests//Flashpost-tests/flashpost.db", ...}. Consequently, when another team member accesses the repository, they can view the collection, but upon attempting to send a request, all files are re-saved with their home directory path, replacing the original files. This inflates the commits of each developer every time the extension is used. Is there a way to set the path to the workspace instead?

- We're encountering a similar issue with file uploads in the request body. Files are consistently saved with the home directory path. This means that when another team member attempts to send the request, they're unable to access the other user's home directory, even though the required file is within the same repository.

Additionally, here are the settings we've configured in the repository:

```json
"flashpost.saveDataToWorkspace": true,
"flashpost.workspaceDataRelativePath": "tests"
```
Is there a feasible solution to address these challenges?

Thank you very much for your attention to this matter.

Best regards

**Comment by subasraj** [comment]
Hi,
Where do you see "{"filename":"/home/Username/workspace/tests//Flashpost-tests/flashpost.db", ...} Can you please share some screen shots?

**Comment by marcoberb** [comment]
I can confirm that the absolute path is inserted into each of the flashpost ".db" files. 

Here are my settings:
```json
"flashpost.saveDataToWorkspace": true
```

**Comment by kryopix** [comment]
Hi,

Thank you for responding so promptly.

The issue occurs across all files. As shown in the screenshot, the entire path to the file is being saved instead of being relative to the {workspace}. This means that whenever another developer collaborates on the same project and opens Flashpost, they can see the collection and submit requests within it. However, when they attempt to send a request, all files are regenerated in the repository with their home directory path and he have to remove the changes or he has to commit his changes even when they have nothing changed in the reuqest itself.

![image](https://github.com/subasraj/flashpost-support/assets/26937559/32a310d0-91f4-4de0-9a62-03a2df1114db)

Similarly, if they make changes to a request and link a file from the repository, the file's path within the request is saved with the complete path, including their home directory, rather than being relative to the workspace. Although the file itself exists in the same repository, since they have their own clone of the repository in their home directory, they cannot use the file.

Additionally, I formatted the JSON file with a prettifier to make the section more readable for the screenshot.

![image](https://github.com/subasraj/flashpost-support/assets/26937559/e028ccf2-773c-4b44-ad68-cc116cd42c5b)


Thank you for looking into this matter.

**Comment by subasraj** [comment]
Changing the path is not possible since we use lokijs DB. The work around will be a pre-commit script like below and set a environment varaible for "workspacepath"

[precommit.txt](https://github.com/subasraj/flashpost-support/files/14272442/precommit.txt)
