### ISSUE TITLE
(new feature request) Snippets or random value substitution 

### ISSUE THREAD

**Issue by tvjames2007** [subasraj/flashpost-support#29]
I've never submitted a request on Github before, apologies if I'm doing it wrong or in the wrong place.  (Or if it exists and I'm just missing it, please educate me and I'll be forever grateful.)

I am looking for either Snippet support in Flashpost or support for local random variables as a new feature.

We recently were told at work "get off Postman immediately and switch to VS Code + Flashpost" On Postman, I was able to used some of the random values https://www.geeksforgeeks.org/dynamic-variable-guid-inside-pre-request-in-postman/ for submitting test data in my API calls.

I haven't discovered how to do this in Flashpost.  I asked on Stack Exchange thinking I was just doing it wrong and the responses so far suggest it's not possible but that I should submit a feature request.

**Comment by subasraj** [comment]
Hi,
If you want to use variables like for example {{serverName}} open the "Environment" tab and add a Variable Named "serverName" with a Value inside Global or create your own environment and add to it.

**Comment by subasraj** [comment]
Hi @tvjames2007 will add this feature.

**Comment by subasraj** [comment]
Hi @tvjames2007 I have added this feature now. For a complete list please see https://github.com/subasraj/flashpost-support/blob/main/random-variables.md
