### ISSUE TITLE
URL parameters are not supported

### ISSUE THREAD

**Issue by tsekki** [subasraj/flashpost-support#3]
Coming from ThunderClient, my queries do not work out-of-the-box after the import.

Example: 

GET localhost:3000/users/{id}

I expect that {id} in URL parameter would be added as parameter as query params are added so I can dynamically make queries with same URL. 

Either URL parameters are not yet supported or plugin is using different placeholder format.

ps. thanks for this drop-in replacement!

**Comment by subasraj** [comment]
Hi
Variable substitutions work for {{variable}} like in Postman. Please try GET localhost:3000/users/{{id}}
