### ISSUE TITLE
[suggestion] relative to project root paths in `.db` files

### ISSUE THREAD

**Issue by BananaAcid** [subasraj/flashpost-support#30]
Thanks for all the great updates!

I am developing on multiple devices (Remote VM, Laptop, Desktop, vscode.com) and I noticed, the paths in the `.db` files change around. So started to manually change them to a relative-to-project-root dir, to prevent git commits for these each time I try something out.

example: flashpost.db
`{"filename":"./Flashpost-tests/flashpost.db" ...`

Could be helpful (to me) ;)

**Comment by subasraj** [comment]
Changing the path is not possible since we use lokijs DB. The work around will be a pre-commit script like below and set a environment varaible for "workspacepath"

[precommit.txt](https://github.com/subasraj/flashpost-support/files/14272442/precommit.txt)
