### ISSUE TITLE
response character encoding problem 

### ISSUE THREAD

**Issue by muhammedfurkan** [subasraj/flashpost-support#31]
Greetings,

There are no words to say about the features and operation of the application. An excellent plugin has been made. The error I encountered seems to be a character encoding problem as a result of api requests. I observed that there are problems with UTF-8 Turkish characters. I share the screenshot about the error in the attachment.

![image](https://github.com/subasraj/flashpost-support/assets/9547040/af11d699-0a24-4038-a079-49164e209c06)

**Comment by subasraj** [comment]
Hi, 
Can you please share a sample url to try and recreate this issue from my side?

**Comment by muhammedfurkan** [comment]
hi,

https://portal.radikalegitim.com/api/v2/subeler-navbar?sube_turu=EGITIM_KURUMU

**Comment by subasraj** [comment]
Hi,
The response you see is the "Raw View" which will be the same of what you when you open the url in any browser "https://portal.radikalegitim.com/api/v2/subeler-navbar?sube_turu=EGITIM_KURUMU" Click the "Tree View" and you will see the turkish characters. See image below.
![image](https://github.com/subasraj/flashpost-support/assets/25518421/9d3dcfc3-efd5-4341-ae0f-c2f3c5c6f6f2)

**Comment by muhammedfurkan** [comment]
> Hi, The response you see is the "Raw View" which will be the same of what you when you open the url in any browser "https://portal.radikalegitim.com/api/v2/subeler-navbar?sube_turu=EGITIM_KURUMU" Click the "Tree View" and you will see the turkish characters. See image below. ![image](https://private-user-images.githubusercontent.com/25518421/311385084-9d3dcfc3-efd5-4341-ae0f-c2f3c5c6f6f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzgxNDAsIm5iZiI6MTcxMDA3Nzg0MCwicGF0aCI6Ii8yNTUxODQyMS8zMTEzODUwODQtOWQzZGNmYzMtZWZkNS00MzQxLWFlMGYtYzJmM2M1YzZmNmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEzMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYWRmMzhjMDNhZjA2NmZlMGE3Y2Q2OGI4MWU4Njk1YWEzZmI3YjAyMzYzYmUyNzI5MmU5YzI0M2MzZjIxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTRjAXvS8Yo2SLeEuDs9_-rm0oaUqegixyCtL8ABHQU)

Yes, that's right. but can there be an improvement to make the Turkish characters appear properly in the other view as well?

**Comment by subasraj** [comment]
No. I don’t think we can and should change the raw view. There is a reason it’s called raw view.
