### ISSUE TITLE
Flashpost unreadable with Gnome 45/Linux

### ISSUE THREAD

**Issue by Peter-Ries** [subasraj/flashpost-support#32]
Hi,

I just switched from Mac to Linux (Endeavour/Arch) with Gnome 45 (GTK) and VSCodium. The Flashpost page looks incomplete. Some items are not being shown. I checked against a Linux with Plasma 6 (Qt). This looks like on Mac - all good here. 

This is a screenshot of the "new request" page:

![image](https://github.com/subasraj/flashpost-support/assets/48622005/859308ad-59b3-460f-a900-db6211a910c5)

I have googled around but could not find anybody else with this problem, so maybe just me?

**Comment by Peter-Ries** [comment]
using --disable-gpu switch solves it...

**Comment by subasraj** [comment]
Hi,
Good to know that you have solved the issue
