### ISSUE TITLE
How to set a variable from response?

### ISSUE THREAD

**Issue by www-chique** [subasraj/flashpost-support#34]
First of all, great work on the Flashpost plugin. I really love how intuitive it is, and how much effort you've put in it.

![image](https://github.com/subasraj/flashpost-support/assets/29447216/b6131468-f2ba-4b28-9b60-11675b661f44)
I'm not sure if I have to configure something, or it's an issue, but when I go to the "set variable" tab, it looks empty.

**Comment by subasraj** [comment]
Hi
Looks like something is wrong with your collection. Please try creating a new collection and a new request and see if you can set the response variable.
