### ISSUE TITLE
UTF-8 Characters are not displayed in response panel (raw-view)

### ISSUE THREAD

**Issue by PedramDarapanah** [subasraj/flashpost-support#36]
when dealing with utf-8 characters in api responses, it displays as unicode escape sequences , for example 
response from api is :
```
{name:"علی عماد"}
```
but in response panel's raw view it is :
```
{name:"\u0639\u0644\u06CC\u0020\u0639\u0645\u0627\u062F"}
```

**Comment by subasraj** [comment]
Yes raw view is meant for showing the raw response
