### ISSUE TITLE
Address bar not visible

### ISSUE THREAD

**Issue by mesaja2006** [subasraj/flashpost-support#39]
Hello,
I have an issue with the flashpost when the option **Save Data To Workspace** is enabled. On my computer the address bar is visible, but on the other user account which has clone the repository to his workspace with flashpost db files the address bar is not visible.
![image](https://github.com/subasraj/flashpost-support/assets/107139526/a53c24aa-6b9f-4157-8270-6f609ebd7f71)

The test are works fine.

**Comment by Rakkoc** [comment]
its came reset vscode after.

**Comment by sanderkooger** [comment]
I'm experiencing the same issue. 

I was working with Save Data To Workspace on, and there was no address bar. Then I turned Save Data To Workspace off restarted VS Code and reimported the collection and voilà it works. 

@Rakkoc did you get it working? if so how? 

@subasraj is there a fix?

**Comment by sanderkooger** [comment]
Relates to https://github.com/subasraj/flashpost-support/issues/35

**Comment by sanderkooger** [comment]
I wanted to see if I could make a PR and fix it. But unfortunately, this repo does not contain code. 

@subasraj Is the source available somewhere? Or is the only thing that's open sourced, the documentation?

**Comment by subasraj** [comment]
@Rakkoc @mesaja2006 @sanderkooger I have fixed this issue in the latest version 1.1.82

**Comment by sanderkooger** [comment]
@subasraj Its working. Thanks a lot!!!

**Comment by subasraj** [comment]
@sanderkooger Please leave a review if you like my extension.
