### ISSUE TITLE
Document for using environment variable / path param

### ISSUE THREAD

**Issue by NamesMT** [subasraj/flashpost-support#40]
There is currently no document to use environment variable and path param that I could find, and the usage of path param is different then Thunder Client.
Made me nearly uninstalled till I found the way to import from Thunder Client and see how path param is used.

**Comment by subasraj** [comment]
Will add. If you can also document and send it to me it will be great. I will add it.

**Comment by NamesMT** [comment]
Hi @subasraj, not trying to be mean or anything, but you should keep the issue as Open for better visibility and prob someone would see it and help.

**Comment by programatix** [comment]
I'm facing the issue. So, how do we use the path param? Putting something like, `{{taskId}}` doesn't work.
