### ISSUE TITLE
Using variable in Path Variable doesn't work

### ISSUE THREAD

**Issue by programatix** [subasraj/flashpost-support#42]
Using variable in `Path Variable` doesn't work.

![image](https://github.com/subasraj/flashpost-support/assets/3293865/b58f7b13-7c6d-4707-862f-244b54deda75)

If I replace it with an actual value, it works.

![image](https://github.com/subasraj/flashpost-support/assets/3293865/07415fa5-5933-466f-a4a3-d03013e66cbf)

**Comment by subasraj** [comment]
Use {{taskId}} in the URL directly instead of :id
