### ISSUE TITLE
Add plain text response support to the "Set the variables from the response" feature

### ISSUE THREAD

**Issue by Albert-Gao** [subasraj/flashpost-support#43]
Hi, great extension! I love it. 😊

Just wonder, any way to add a text response type in the "Set the variables from the response" feature?

It currently support head/cookie/json response which are quite helpful, however, there is a case that the response is plain text, and I want to set this whole text to a variable.

That's it, thanks in advance. :)

**Comment by subasraj** [comment]
Hi,
Please update to version 1.1.80 and try now. You have the option "Text Response". Please give me a review if you like my extension.
Thanks,
Subas

**Comment by Albert-Gao** [comment]
![image](https://github.com/subasraj/flashpost-support/assets/18282328/ea25dd6f-e14f-437a-9f84-9cc2fe9feb4e)

added, thanks so much mate!

@subasraj  :)
