### ISSUE TITLE
flashpost.db filename relative problem

### ISSUE THREAD

**Issue by Rakkoc** [subasraj/flashpost-support#44]
im set my relative path and Save Data to Workspace, 

![image](https://github.com/user-attachments/assets/6010a4d5-7d93-4b58-b3d5-1bd45b0a193e)
![image](https://github.com/user-attachments/assets/7e4b759f-ee54-464e-8843-c9135214374c)

its save my folder is good. But in the flashpost.db file its includes my path. I dont want send my path to my git server.

![image](https://github.com/user-attachments/assets/a8929f01-bc89-49d0-9628-f999fdaab08f)

**Comment by subasraj** [comment]
Use this below script to update the db files
https://github.com/subasraj/flashpost-support/files/14272442/precommit.txt
