### ISSUE TITLE
Amended Content-Type header overwritten when viewing Body

### ISSUE THREAD

**Issue by rickboy** [subasraj/flashpost-support#45]
I have an API that I am attempting to connect to, as part of it's spec, sending an update via a PATCH requires an amended header. It requires a value similar to the ones required by ASP.NET core web apis - https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-8.0.

Flashpost handles the initial setting of the header, however, if I view the Body -> Raw tab after changing the Content-Type header the header reverts back to the selected format. In this case the Raw type is JSON, so the Content-Type header is set back to "application/json"

**Comment by subasraj** [comment]
@rickboy I have fixed the issue. Please update the extension to version 1.1.81 and try again. Please add a review if you like the extension. Thanks.
