### ISSUE TITLE
URL field dissapeared 

### ISSUE THREAD

**Issue by glaucomorais** [subasraj/flashpost-support#46]
When I try to make a request, the URL field dissappear and in the Extension Host (Remote) this error is shown:
```
[error] TypeError: Cannot read properties of undefined (reading 'trim')
	at /home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:1811457
	at Array.forEach (<anonymous>)
	at v (/home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:1811365)
	at k (/home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:1811569)
	at /home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:1817543
	at /home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:508122
	at /home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:507441
	at /home/glauco/.vscode-server/extensions/vasubasraj.flashpost-1.1.81/dist/extension.js:7:505836
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

I'm using VSCode WSL extension with Ubuntu 24.04 LTS in WSL2.

### My VSCode info:
**Version:** 1.91.1 (user setup)
**Commit:** f1e16e1e6214d7c44d078b1f0607b2388f29d729
**Date:** 2024-07-09T22:06:49.809Z
**Electron:** 29.4.0
**ElectronBuildId:** 9728852
**Chromium:** 122.0.6261.156
**Node.js:** 20.9.0
**V8:** 12.2.281.27-electron.0
**OS:** Windows_NT x64 10.0.19045

**Comment by subasraj** [comment]
@glaucomorais please share your collection if you can and I will try to debug the issue.

**Comment by glaucomorais** [comment]
I was working in a project without collections. I just opened the Flashpost and clicked in `New request` and that's it.

My home computer is working normally, but my work computer is having this problem.

Sorry I didn't detail it correctly.

**Comment by glaucomorais** [comment]
After removing the .env file from the workspace root, the error stopped happening. 😣

**Comment by subasraj** [comment]
Can you please share some details about that .env  file so that i can debug and fix the issue

**Comment by subasraj** [comment]
@glaucomorais I have fixed this issue in the latest version 1.1.82

**Comment by glaucomorais** [comment]
Cool. I'll check if my version is updated and test tonight.

**Comment by subasraj** [comment]
@glaucomorais Please leave a review if you like Flashpost

**Comment by glaucomorais** [comment]
It's working now.

All right, @subasraj.

Thanks.
