### ISSUE TITLE
[Feature Request] - Ability to save request into a collection

### ISSUE THREAD

**Issue by abulka** [subasraj/flashpost-support#48]
I can't figure out how to save a request into a collection!

Yes I can create a request within a collection in the first place, and that will be saved. But when I hit the big button that says "New Request" I cannot figure out how to save that request into a collection. 

Seems like a huge UI omission which confused me for a long time. Sure you could argue that its a "temporary" request area where you can muck around - but when you get it right and want to save it, what do you do? Manually copy each setting into a proper request which you have explicitly created within a collection? Why not add a button "Save into Collection?"

**Comment by subasraj** [comment]
New requests will be saved in History tab and you can save that to a collection
![image](https://github.com/user-attachments/assets/9e7507e6-da44-49a7-aded-97c3c53958c7)

**Comment by abulka** [comment]
Ah, I see - thanks.

**Comment by abulka** [comment]
Workflow is still a bit strange:
 
- hit "New Request"
- type in google.com, 
- it appears in history ok. 
- now change the url in that request to example.com (do we ever get urls right the first time?) - Send
- the request with the new url example.com doesn't appear in history, thus can't be saved into a collection via the technique outlined above.

Hitting New Request doesn't create a new request, just takes me to that one existing request. The only way to get my edited url example.com into a collection is to close the "new request" tab (losing my work), open up a new request tab, type in example.com and now it appears in history. But if I make a typo in my url and have done a send, I have to start again.

Of course I understand that creating a request directly inside a collection means I can edit the url, albeit have to rename the request manually to reflect any changes I make to the semantics of the request. But this issue is about the workflow of the "New Request" which is not ideal or intuitive. 

The intuitive way (for my way of thinking) is that new request always creates a fresh, new request tab, and it would have a prominent save button. Arguably changing the url of an unsaved request would create a fresh history entry with that url.
