### ISSUE TITLE
[Feature Request] - Preview files and .svg images

### ISSUE THREAD

**Issue by abulka** [subasraj/flashpost-support#49]
When the content type is a file, you don't show it and instead I have to download it to a file on disk and preview it there myself. 

It would be great if FlashPost would preview common files like text, .svg, .png rather than needing to do this laborious download step.

EVERY other postman-like tool does this - FlashPost is the only one that does not!
- Rapid API client - yes
- Thunder Client - yes
- Postman - yes
- FlashPost - no

**Comment by subasraj** [comment]
@abulka I have added the functionality to display text files now. Please try and let me know. Please add a review if you like Flashpost.
