### ISSUE TITLE
Support Custom Data Location being able to use workspace reference

### ISSUE THREAD

**Issue by dainbrump** [subasraj/flashpost-support#5]
I'm not sure what would be required, but is there any way to support using something like `${workspaceFolder}` as the data location? This would aid in saving any collections and such with the project source.

**Comment by subasraj** [comment]
Hi,
I have made the changes for you, update to latest version 1.1.46. If you like to save requests data in your current workspace use "Save Data to Workspace" setting. You can also select a relative path by using "Workspace Data Relative Path" setting.

Please post a review if you like my extension.

Thanks,
Subas

**Comment by dainbrump** [comment]
This is fabulous. Thank you for the quick response. This makes all the difference in keeping things tidy, relative to the project and shareable through git. Perfection!

**Comment by subasraj** [comment]
Thanks for the review :)
