### ISSUE TITLE
[Feature Request] - default headers for POST arguably not suitable

### ISSUE THREAD

**Issue by abulka** [subasraj/flashpost-support#50]
Default headers for POST add `application/json` etc. and don't work for most of my use cases. I have to remove almost all of them.

  | Header | Value |  
-- | -- | -- | --
  | Cache-Control | no-cache |  
  | Accept | */* |  
  | User-Agent | Flashpost |  
  | Accept-Encoding | gzip, deflate |  
  | Connection | keep-alive |  
  | Content-Type | application/json |  

Is there a way of configuring this - a header presets feature like postman could be good too, with a default preset.

The defaults by postman and thunderclient etc. are more minimal.

**Comment by subasraj** [comment]
Removed unwanted headers. Install the latest version and try.
