### ISSUE TITLE
Save Data To Workspace with Remote Explorer

### ISSUE THREAD

**Issue by LaCocoRoco** [subasraj/flashpost-support#51]
Is it possible your Extension does not respect Remote Development?
The New Request is missing the URL because it probably tries to use the home directory of the local machine.

![image](https://github.com/user-attachments/assets/6e8482e6-681c-4019-9916-34b246fbc743)

![image](https://github.com/user-attachments/assets/688a180d-f0e9-42be-9eb6-8654d97e55a0)

**Comment by LaCocoRoco** [comment]
I recognized there are some more issues open regards this problem. I also think it does not have to do anything with the Remote Explorer. If using the default data location $Home/Documents/ everything is saved in the home/andreas/Documents/Flashpost directory of the remote machine. But when using the "Save Data To Workspace" Setting the New Request Panel bugs out.

**Comment by subasraj** [comment]
@LaCocoRoco I have fixed this issue in the latest version 1.1.82
