### ISSUE TITLE
Reordering Requests

### ISSUE THREAD

**Issue by nextonphotos** [subasraj/flashpost-support#54]
I thought I used to be able to drag and drop requests in the FlashPost pane to reorder them or to sort them into folders.  If so, it no longer seems to work.  If I try to drag one, I get a ghost of the item and a blue line appears to make it look like things are working, but moving and dropping have no effect.

My main use case for this is when I want to make a similar request to one that exists. I duplicate the existing one, make my changes, and then want to sort it into the correct folder, but cannot currently.

Any thoughts as to what's up?

Thanks!

**Comment by subasraj** [comment]
It works fine for when i try now. There is no issue. Please update your vscode to latest version and update Flashpost to latest version.

**Comment by nextonphotos** [comment]
SO, I tried a fresh install of both vscode and FlashPost, and the reordering works, though there is still something odd about it.  When I drag an item to a new spot, it moves and the enter new description dialog drops down. Is that expected behavior?

Thanks!
