### ISSUE TITLE
Option to add base URL to collection

### ISSUE THREAD

**Issue by krokand** [subasraj/flashpost-support#59]
It would be a nice feature to have the possibility to add a base URL to a collection. Like "https://example.com/"
Then you could just add: 
"/docs"
"/users"
etc. in each request.

**Comment by metawops** [comment]
That's what environments and variables therein for. 😉 
Create a new environment, add a variable `baseURL` and set its value to `https://example.com`.
Then set this environment to be active via its burger menu.
Then, in your request, reference the variable by writing `{{baseURL}}`.
For me, this works with the second time you make the request. The name of the variable (including the braces) should turn green then.
