### ISSUE TITLE
postman import issue

### ISSUE THREAD

**Issue by muhammedfurkan** [subasraj/flashpost-support#6]
Hello i am getting like that issue for already exported postman collection to import flashpost

`14-Dec-2023 08:12:46  error::importPostmanCollection(): - Error Mesaage : TypeError: Cannot read properties of undefined (reading 'raw')`

**Comment by subasraj** [comment]
Hi,
What version of Flashpost you are using? Please update to the latest version and try again.
What version of the Postman collection you are trying to import?
If possible please send me the Postman collection you are trying to import so that I can check and debug it.

**Comment by muhammedfurkan** [comment]
![image](https://github.com/subasraj/flashpost-support/assets/9547040/6d3f74a3-fa74-44a6-935c-a636a7524c16)

![image](https://github.com/subasraj/flashpost-support/assets/9547040/25d69b0a-2298-43b0-9cdb-328762456d53)


[OffisMekan API Copy.postman_collection.json](https://github.com/subasraj/flashpost-support/files/13682596/OffisMekan.API.Copy.postman_collection.json)

**Comment by subasraj** [comment]
Fixed the issue. There was an invalid request name "New Request". Please try the latest version 1.1.49
{
	"name": "New Request",
	"request": {
		"method": "GET",
		"header": []
	},
	"response": []
}

**Comment by muhammedfurkan** [comment]
thank you 😍

**Comment by subasraj** [comment]
Can you Please post a review if you like my extension. 🙂
