### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by mserajnik** [subasraj/flashpost-support#60]
There is a security issue in this extension; I won't go into further details here but I strongly recommend not to use it for the time being.

I couldn't find a way to privately contact the extension developer (@subasraj) and VS Marketplace support decided not to act when I told them about it and instead referred me to this repository (even after telling them there is no apparent way to contact the developer in private).

@subasraj: contact me via email (see my GitHub profile) and provide proof that the email you are using is yours (e.g., by adding it to your GitHub profile or adding a note to this repository) and I will provide the details.

**Comment by maximejobin** [comment]
That issue is as responsible as it gets. You went above and beyond.

**Comment by subasraj** [comment]
@mserajnik will send you an email now

**Comment by mserajnik** [comment]
Just for anyone else reading this: @subasraj has sent me an email and I have provided him with the details.

I’ll leave this GitHub issue open for him to close once it is fixed.

**Comment by subasraj** [comment]
Fixed
