### ISSUE TITLE
Error Importing - Invalid environment file

### ISSUE THREAD

**Issue by jmac-slash0** [subasraj/flashpost-support#62]
When I export environment variable data from Thunder Client and try to import it into Flashpost I get the following error: ```Error Importing - Invalid environment file.```

So what format is expected? Also a better error and some documentation for what import format should be would be very helpful. Also, I don't see any option to export from Flashpost?

Here is an import file sample json:

```
{
    "clientName": "Thunder Client",
    "environmentName": "(Global Env)",
    "environmentId": "fc22eede-9536-4c0b-92e0-d7985597f364",
    "dateExported": "2024-10-10T21:13:34.532Z",
    "version": "1.2",
    "global": true,
    "variables": [
        {
            "name": "Hello",
            "value": "World"
        }
    ],
    "ref": "au_iP_0O9rOgbrNd9kgmMaLFSbukp7F9PIafbbJUIFmqxBmPW8_e7YnhKwhihgu6tFWhV6brtVDn0xRLi9nrLQ"
}
```

**Comment by babych-a** [comment]
Had same problem. 
Fix with checking json of _**flashpost**_ and then ask modify **_chatGPT_**

Here is flashpost json


```
{
  "app": "Flashpost",
  "id": "8ccd8a86-2baa-442b-a3c1-8f22dd079754",
  "name": "Global",
  "version": "1.0",
  "type": "variables",
  "createdTime": "23-Oct-2024 15:39:08",
  "exportedDate": "23-Oct-2024 15:56:48",
  "isActive": true,
  "data": [
    { "isChecked": true, "key": "change", "value": "name", "type": "global" },
    { "isChecked": true, "key": "hello", "value": "world", "type": "global" }
  ]
}
```

**Comment by igebuntu** [comment]
Hi,

Make the following adjustments to the JSON file:

- Rename "clientName" to "client"
- Delete "collectionId" attribute
- Modify "version" to "1.1"
- Remove "ref" attribute

For me this worked importing the TC Collection JSON files to Flashpost.

**Comment by metawops** [comment]
In Thunder Client don't export the environment directly.
Instead, go to the three-dots-main-menu and choose "Convert To Postman".
In the upcoming list choose "Convert Environment".
Use _this_ file to import into FlashPost.

**Comment by subasraj** [comment]
Fixed the issue. Install the latest version and try.
