### ISSUE TITLE
Request for documentation on variable usage

### ISSUE THREAD

**Issue by jsanta** [subasraj/flashpost-support#65]
Is there a chance that you include in the documentation how to use the  variables  Flashpost can set  from the response, with some 
 examples?
I've tried using $variable and {{variable}} and couldn't make them work.

The use case I'm trying is a login request that returns a json like: 
```
{
  token: "token-uuid-value"
}
```
which I'm storing in an environment value called `devToken`.
I'm trying to use this `devToken` variable in other requests from my collection.

Thanks in advance.

**Comment by metawops** [comment]
Would like to know that, too.

**Comment by subasraj** [comment]
Use like {{devToken}}

**Comment by metawops** [comment]
Yes, okay, once such a variable got a value we'd use it like that.

However, my problem is: setting a value.

Here's a request and its JSON response and I'm wondering what to type in the "Value" field:

<img width="1403" alt="SCR-20241111-lvag" src="https://github.com/user-attachments/assets/311722da-4cf9-455f-ab2b-108cf14c88ef">

You see that tried the name of the array from the response but had no luck, the variable `astro_bodies` had no value after I made the request:

<img width="596" alt="SCR-20241111-lvxv" src="https://github.com/user-attachments/assets/fd2c2a77-2a88-43c1-aef1-eb50a4422ae8">

So how do I select something from the JSON response? Did you by any chance implement JSONpath so I could use a JSONpath string to navigate to a specific value of the key I'm interested in?

In this special case, by writing `bodies`, I'd get back an array. Is an array even possible to be a value of a variable in FlashPost?

So many questions ... Some documentation would be nice ... 😉

**Comment by subasraj** [comment]
Arrays cannot be store as vairables. But you can use root.data.bodies[0] or root.data.bodies[1] and so on

**Comment by metawops** [comment]
So you're not planning on implementing a JSONpath interpreter, did I get that right from your answer?

**Comment by metawops** [comment]
Also, it's still not working for me.
I learned from your answer that `root` is to be used to start the expression.
Here's an example and setting the `moon_age` variable is not working with this expression `root[0].Age` – why? 

<img width="1822" alt="SCR-20241117-njgg" src="https://github.com/user-attachments/assets/960c0cb2-0ce6-4c99-8cb7-3d6e84018255">


`root.[0].Age` isn't working either.
This is all pure guess work and as the title of this issue says: a bit of documentation would be really nice!

**Comment by subasraj** [comment]
I don't know the problem you have, it works for me.

**Comment by metawops** [comment]
Well, lucky you.
Still not working for me. 🤷‍♂️ 
Maybe I'm misunderstanding how it works.
But having no documentation it's all just guess work.
