### ISSUE TITLE
The Raw View of any request is displayed in a single line

### ISSUE THREAD

**Issue by alexverdin** [subasraj/flashpost-support#67]
For a few days now, whenever I make an HTTP request, the Raw View of the response is shown in a single line, making it impossible to debug.
I have tried disabling all extensions except FlashPost, tested different APIs, and the problem persists.
Tree view, however, displays correctly.
- VSCode version: 1.95.1
- FlashPost version 1.1.84

This is how the raw view used to look:
![image](https://github.com/user-attachments/assets/c23c115a-250d-471c-b166-2c2722464379)

This is how it looks now:
![image](https://github.com/user-attachments/assets/9694ee1e-8862-4189-a4c7-c92074d6b4eb)

This is how it looks from the PokeAPI:
![image](https://github.com/user-attachments/assets/e6e5880d-cbe2-4e87-bd14-6525116cccb4)

**Comment by Kotaless** [comment]
I'm experiencing the same issue with every format. Changing the formatter settings had no effect.

**Comment by subasraj** [comment]
What is the content type in the response header ?

**Comment by Kotaless** [comment]
> What is the content type in the response header ?

For me, both application/json and application/xml are failing to format.
I can't even format my request body.
![image](https://github.com/user-attachments/assets/10cd8b20-59ae-4292-ae80-1df0665e0919)

**Comment by subasraj** [comment]
See below for response Headers

![image](https://github.com/user-attachments/assets/c3e0acbe-d09b-41c5-8cb6-3237f6616187)

**Comment by subasraj** [comment]
@Kotaless @alexverdin Downgrade your vscode to 1.94.2 https://code.visualstudio.com/updates/v1_94
There is an issue with monacco editor in 1.95.x version
