### ISSUE TITLE
Request Headers not being saved

### ISSUE THREAD

**Issue by martinvilche98** [subasraj/flashpost-support#68]
After inserting a new header in request and saving, the header is not present when you reopen.
Things seem to save fine at times, but once in a while it kinda breaks.

Example GIF:

[![SyWHl.gif](https://s11.gifyu.com/images/SyWHl.gif)](https://gifyu.com/image/SyWHl)

in Flashpost v1.1.84

--- 

Update, apparently this issue only occurs with the `Cookie` Header.

**Comment by subasraj** [comment]
I have fixed the issue. Please try again.

**Comment by martinvilche98** [comment]
Thank you so much, you're a legend.
