### ISSUE TITLE
Unable to delete collection

### ISSUE THREAD

**Issue by brandsr** [subasraj/flashpost-support#7]
Nothing happens when trying to delete a collection. Using the FlashPost extension with defaults through remote-SSH.

**Comment by subasraj** [comment]
Can share a sample file please will try to debug.

**Comment by brandsr** [comment]
No need to have an example file, its something in the interface. But somehow the delete does work now 🤷‍♂️

**Comment by subasraj** [comment]
Please export and send me the collection
