### ISSUE TITLE
Raw Response Always Formatted on a Single Line

### ISSUE THREAD

**Issue by abozaid01** [subasraj/flashpost-support#72]
First of all, thank you for creating the Flashpost extension! It has been incredibly helpful in my development workflow, and I truly appreciate the effort you've put into building this tool.

However, I noticed an issue where the raw response is always formatted as a single line, which makes it difficult to read and debug the responses, especially for nested JSON objects. Previously, the responses were displayed in a readable, nested format, which was much easier to work with.

![raw-response-single-line](https://github.com/user-attachments/assets/4a5984bd-a394-4f4d-8e3e-d57cf1085303)

**Comment by subasraj** [comment]
@abozaid01 Downgrade your vscode to 1.94.2 https://code.visualstudio.com/updates/v1_94
There is an issue with monaco editor in 1.95.x version
