### ISSUE TITLE
Keep `language` and `options` in Code snippet

### ISSUE THREAD

**Issue by c4ldas** [subasraj/flashpost-support#73]
Every time I make a request and go to the Code Snippet, it always defaults to 
Language:`JavaScript`
Options: `Axios`

Is there a way to keep the same language and options previously chosen? Or have an option in settings to choose the default one?

**Comment by subasraj** [comment]
@c4ldas  I have made an update to save the selection. Please install the latest version and try again. Also if you like my extension so far Please give a good review.

**Comment by c4ldas** [comment]
Hey @subasraj thank you for the update. I can see it works fine on first click, but the next click (or after some more clicks), it changes again to Axios. Check this video below:

https://github.com/user-attachments/assets/77c922b5-63f6-4a56-b3cd-37973fcb79b8

Also, I don't know if it is related to the extension itself, but I need to click twice on the dropdown menu to enable it.
I have just written a review on VS Marketplace, thank you so much for creating such a good extension!

**Comment by subasraj** [comment]
Hi @c4ldas im  not able to start the video. Can you please upload again

**Comment by c4ldas** [comment]
> Hi @c4ldas im not able to start the video. Can you please upload again

Thanks for taking your time to check that, I uploaded the video to Youtube, you can check it here:

https://youtu.be/mTM0DMucThM

**Comment by subasraj** [comment]
Hi @c4ldas Please try the latest version, it should work now.

**Comment by c4ldas** [comment]
> Hi @c4ldas Please try the latest version, it should work now.

Great, I have just tested it and it's keeping the same Language and options as expected! Thank you very much for that!
