### ISSUE TITLE
Save Data To Workspace stops extensions from working

### ISSUE THREAD

**Issue by nelson-saldanha** [subasraj/flashpost-support#8]
Hi, 
I’m having a problem when activating the setting `flashpost.saveDataToWorkspace` the extension stops working.
Tried leaving the setting `flashpost.workspaceDataRelativePath` empty or with different values but it still did not work.
Trying to access the error log I get `command 'flashpost.openErrorLog' not found`
Disabling the setting `flashpost.saveDataToWorkspace` makes the extension work again.
I’m using VSCode 1.85.1 on Windows 11

**Comment by subasraj** [comment]
Hi,
I have fixed the issue. Please update to the latest version 1.1.52 and try again.

Also please leave a review if you like my extension :)

Thanks,
Subas

**Comment by nelson-saldanha** [comment]
Thank you, it works correctly now.
Appreciate the fast response!
Will leave a review after I test it a bit :)
