### ISSUE TITLE
(Feature) Light theme mode 

### ISSUE THREAD

**Issue by nelson-saldanha** [subasraj/flashpost-support#9]
Hello,
I know it's unconventional but I'm using a light theme, is there a way to customize the font color / theme so I can have better contrast.
![image](https://github.com/subasraj/flashpost-support/assets/8662023/12d439fd-30eb-48e4-8196-8b460b44ba8a)
Cheers

**Comment by subasraj** [comment]
Try version 1.1.53, I have made the changes.

**Comment by nelson-saldanha** [comment]
Looks good.
 I'll be trying the extension out in my current project and then leave feedback and a review. I'm liking what I've seen so far.
Thank you so much for your prompt work and response.
